name: Continuous Integration/Delivery
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Fetch CI/CD Tool
        run: |
          curl -L -o cicd.zip https://github.com/visola/cicd-toolbox/releases/latest/download/cicd_linux_amd64.zip \
            && unzip -d cicd-dir cicd.zip \
            && cp cicd-dir/cicd cicd

      - name: Calculate Next Version
        run: |
          ./cicd semantic-release version-file visola/photos-frontend
          cat .version

      - name: Build
        run: |
          npm install
          npm run bundle

      - name: Package
        run: pushd dist && tar -cvzf ../photos-frontend.tar.gz * && popd

      - name: Release Package
        if: github.ref == 'refs/heads/main'
        run: |
          VERSION=$(cat .version)

          ./cicd semantic-release publish-release visola/photos-frontend \
            --github-token ${{ secrets.GITHUB_TOKEN }} \
            --upload photos-frontend.tar.gz
